name: Build and publish @prisma/prisma-fmt-wasm

on: workflow_dispatch

jobs:
  build:
    name: Build and publish @prisma/prisma-fmt-wasm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    # Install nix
    # Copy-pasted from https://github.com/marketplace/actions/install-nix
    - uses: cachix/install-nix-action@v14
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Print input
      env: { THE_INPUT: '${{ toJson(github.event.client_payload) }}' }
      run: |
        echo $THE_INPUT

    - name: Update Cargo.lock and engines source hash
      run: |
        export DATAMODEL_CHECKSUM_FILE=datamodel-0.1.0.sha256sum

        echo 'cargo update...'
        nix run .#cargo update

        echo 'Setting up fake checksum so the build can fail and output the new hash...'
        echo 'sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=' > \
          $DATAMODEL_CHECKSUM_FILE

        echo "Computing and inserting new datamodel checksum"
        export DATAMODEL_CHECKSUM=`nix build 2>&1 1>&2 | awk '/got:/ {print $2}'`

        echo "Installing new datamodel checksum: $DATAMODEL_CHECKSUM"
        echo "$DATAMODEL_CHECKSUM" > $DATAMODEL_CHECKSUM_FILE

    # Build
    - run: nix build .

    #
    # Publish
    #

    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    # - run: bash .github/workflows/setup.sh
    #   env:
    #     CI: true
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Optional but recommended, defaults to "Apply automatic changes"
        commit_message: engines commit ${{ github.event.client_payload.commit }}

        # Optional commit user and author settings
        commit_user_name: prisma-bot
        commit_user_email: prismabots@gmail.com
        commit_author: prisma-bot <prismabots@gmail.com>

    - run: npm publish result --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Slack Notification on Failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_TITLE: 'prisma-fmt-wasm publishing failed :x:'
        SLACK_COLOR: '#FF0000'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
