name: Build and publish @prisma/prisma-fmt-wasm

on:
  workflow_dispatch:
    inputs:
      enginesWrapperVersion:
        required: true
      enginesHash:
        required: false
      npmDistTag:
        required: true
        default: "latest"

jobs:
  build:
    name: Build and publish @prisma/prisma-fmt-wasm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    # Install nix
    # Copy-pasted from https://github.com/marketplace/actions/install-nix
    - uses: cachix/install-nix-action@v14
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    #
    # Update repository for the new engines version and package version
    #

    - name: Update Cargo.lock and engines source hash
      run: nix run .#updateLocks

    - name: Update NPM package version
      run: |
        ENGINES_WRAPPER_VERSION=${{ github.event.inputs.enginesWrapperVersion }};

        if [[ $ENGINES_WRAPPER_VERSION == '' ]]; then
          echo "Engines wrapper version is not defined"
          exit 1
        fi

        echo "Updating the npm package version to $ENGINES_WRAPPER_VERSION"
        nix run .#updateNpmPackageVersion ${{ github.event.inputs.enginesWrapperVersion }}

    #
    # Build
    #
 
    - run: nix build .

    #
    # Commit
    #

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: engines commit ${{ github.event.inputs.enginesHash }}
        commit_user_name: prisma-bot
        commit_user_email: prismabots@gmail.com
        commit_author: prisma-bot <prismabots@gmail.com>

    #
    # Publish
    #

    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Set up NPM token
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - run: npm publish ./result --access public --tag ${{ github.event.inputs.npmDistTag }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    #
    # Failure handlers
    #

    - name: Slack Notification on Failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_TITLE: 'prisma-fmt-wasm publishing failed :x:'
        SLACK_COLOR: '#FF0000'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
