on:
  schedule:
    # Run every Sunday at 12:30 UTC
    - cron: '30 12 * * 0'

jobs:
  update:
    name: Update build dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v16

      #
      # Update flake.lock
      #

      - run: nix flake update

      #
      # Sync wasm-bindgen versions (nixpkgs and Cargo.toml)
      #

      - run: 'nix run .#syncWasmBindgenVersions'

      #
      # Build to confirm that this did not break the build.
      #

      - run: nix build

      #
      # Commit
      #

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update system/build dependencies
          commit_user_name: prisma-bot
          commit_user_email: prismabots@gmail.com
          commit_author: prisma-bot <prismabots@gmail.com>

      #
      # Failure handlers
      #

      - name: Set current job url in SLACK_FOOTER env var
        run: echo "SLACK_FOOTER=<$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|Click here to go to the job logs>" >> $GITHUB_ENV

      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_TITLE: 'prisma-fmt-wasm update-system-dependencies failed :x:'
          SLACK_COLOR: '#FF0000'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
